### ISSUE TITLE
data type in loadRawToDat.m

### ISSUE THREAD

**Issue by dshimaoka** [cortex-lab/widefield#16]
fwrite assumes uint8 if not specified. So 
fwrite(fid, regFrames) will not work if data is single.

I would rewrite as follows:

```
    rawDType = class(imstack);
    fwrite(fid, regFrames, ['*' rawDType]);
```

**Comment by nsteinme** [comment]
Thanks, fixed. The \* isn't necessary here - that's just for fread. 
fread(fid, sz, 'uint16=>uint16'); % read the data as uint16 and return it to me as uint16
fread(fid, sz, '*uint16'); % same, in shorthand
